apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  # use your external IP here
  loadBalancerIP: 35.198.250.18
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: web
